apiVersion: v1
kind: Pod
metadata:
  labels:
    label: docker-compiler
spec:
  hostNetwork: true
  containers:
  - name: jnlp
    image: jenkinsci/jnlp-slave
    workingDir: /home/jenkins
    tty: true
    resources:
      limits:
        memory: "8Gi"
        cpu: "8"
      requests:
        memory: "1Gi"
        cpu: "1"

# details https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/
