apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.3
controlPlaneEndpoint: "<virtual-ip>:6443"
imageRepository: my.artifactory.com/docker-k8s-remote
etcd:
  external:
    endpoints:
