apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-artifactory
  namespace: devops-ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-artifactory
        group: devops-artifactory
    spec:
      nodeSelector:
        jenkins: slave
      containers:
      - name: devops-artifactory
        image: docker.bintray.io/jfrog/artifactory-pro:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_TYPE
          value: postgresql
        - name: DB_USER
          value: artifactory
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: devops-postgresql
        # Make sure to keep the memory java args aligned with the resources definitions
        - name: EXTRA_JAVA_OPTIONS
          value: -Xms1g
                 -Xmx2g
        ports:
        - name: http-port
          containerPort: 8081
        volumeMounts:
        - mountPath: "/var/opt/jfrog/artifactory"
          name: devops-artifactory-home
        # Make sure to keep the resources set with values matching EXTRA_JAVA_OPTIONS above
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 180
          periodSeconds: 10
      volumes:
      - name: devops-artifactory-home
        persistentVolumeClaim:
          claimName: devops-artifactory-claim
      imagePullSecrets:
      - name: devops-docker-reg-secret
---
apiVersion: v1
kind: Service
metadata:
  name: devops-artifactory
  namespace: devops-ci
  labels:
    app: devops-artifactory
    group: devops-artifactory
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 31666
    name: devops-artifactory
  selector:
    app: devops-artifactory
