apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-nginx
  namespace: devops-ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-nginx
        group: devops-artifactory
    spec:
      nodeSelector:
        jenkins: slave
      containers:
      - name: devops-nginx
        image: docker.bintray.io/jfrog/nginx-artifactory-pro:6.7.0
        env:
        - name: ART_BASE_URL
          value: "http://artifactory-pro:8081/artifactory"
        - name: SSL
          value: "true"
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/var/opt/jfrog/nginx"
          name: devops-nginx-volume
        - mountPath: "/var/opt/jfrog/nginx/ssl"
          name: ssl-secret-volume
      volumes:
      - name: devops-nginx-volume
        persistentVolumeClaim:
          claimName: devops-nginx-claim
      - name: ssl-secret-volume
        secret:
          secretName: art-tls
