kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devops-postgresql-claim
  namespace: devops-ci
  labels:
    group: devops-artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
