apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: marslo-cert
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: marslo.jiao@gmail.com
    privateKeySecretRef:
      name: marslo-cert
    http01: {}
