REM  package for atom
apm install active-power-mode-delete
apm install active-power-mode
apm install atom-ctags
apm install clipboard-plus
apm install git-plug
REM  For syntax
apm install ssh-config
apm install langunage-docker
apm install language-generic-config
apm install language-groovy
apm install language-lua
apm install language-markdown
apm install laugnage-robot-framework
apm install language-viml
apm install highlight-selected
apm install quick-highlight
REM  For Markdown
apm install markdown-folder
apm install markdown-mindmap
apm install markdown-perview-plus
apm install markdown-scroll-sync
apm install markdown-writer
REM  For minimap
apm install minimap
apm install minimap-bookmark
apm install minimap-cursorline
apm install minimap-find-and-replace
apm install minimap-highlight-selected
apm install minimap-quick-highlight
apm install minimap-selection
REM  For Python
apm install python-debugger
apm install python-indent
apm install robot-selenium-snippet
apm install autocomplete-python
apm install autocomplete-robot-framework
rem  For Vim Mode
apm install tab-swicher
apm install vim-mode
apm install ex-mode
apm install vim-mode-clipboard-plus
apm install vim-mode-visual-block
apm install vim-surround
