#!/usr/bin/env bash
# shellcheck source=/dev/null disable=SC2086,SC2124,SC2155
#=============================================================================
#     FileName : git-stat
#       Author : marslo
#      Created : 2025-02-15 19:45:31
#   LastChange : 2026-02-12 23:34:05
#=============================================================================

# USAGE:
# # show help
# $ git stat -h or $ git stat -- --help
#
# $ git stat --author "marslo" -l -- --after='2025-01-01'
# statistics for marslo - git@github.com:marslo/ibook.git :
#
# line changes :
#
#   files changed ......................... 100% ( 57/57 )
#   line inserted ......................... 100% ( 2089/2089 )
#   line deleted  ......................... 100% ( 462/462 )

shopt -s extglob

declare -r HERE="$( dirname "${BASH_SOURCE[0]:-$0}" )"
declare -r ME="$(basename "${BASH_SOURCE[0]:-$0}" | tr '-' ' ')"

# @credit: https://github.com/ppo/bash-colors
# @usage:  or copy & paste the `c()` function from:
#          https://github.com/ppo/bash-colors/blob/master/bash-colors.sh#L3
# shellcheck disable=SC2015
test -f "${HERE}/bash-colors.sh" && source "${HERE}/bash-colors.sh" || { c() { :; }; }

function die() { echo -e "$(c R)ERROR$(c) : $*" >&2; exit 2; }
function exitOnError() { if [ $? -ne 0 ]; then echo -e "$(c R)ERROR$(c) : $*" >&2; exit 1; fi; }
function showHelp() { echo -e "${USAGE}"; exit 0; }
function isRepo() { git rev-parse --git-dir >/dev/null 2>&1 || exitOnError 'not a git repo !'; }
function trim() { IFS='' read -r str; echo "${str}" | sed -e 's/^[[:blank:]]*//;s/[[:blank:]]*$//'; }
function padRight() {
  while IFS=':' read -r param value length; do
    if [[ -n "${param}" ]] && [[ -n "${value}" ]]; then
      padlength=${length:-40}
      pad=$( printf '\x2e%.0s' $(seq "${padlength}") )
      printf "%s%s%s\n" "${param}" "${pad:${#param}}" "${value}"
    else
      printf "%s:%s\n" "${param}" "${value}"
    fi
  done
}

function debugLog(){
  case "$1" in --np | --no-pad ) pad=false; shift;; esac
  local str=$( echo -e "$@" | awk '{print "[DEBUG] >> " $0}' )
  echo -e "$(c Wid)${str}$(c)" | padRight
}

function lineChangesStat() {
  local allChanges
  local userChanges
  local debugInfo
  local -a cmd=( git log --shortstat --oneline --format=tformat: )

  allChanges=$("${cmd[@]}" "${GIT_OPT[@]}" |
               awk '{ files+=$1; inserted+=$4; deleted+=$6 } END { print files, inserted, deleted }'
              )
  userChanges=$("${cmd[@]}" "${GIT_OPT[@]}" --author="${author}" |
                awk '{ files+=$1; inserted+=$4; deleted+=$6 } END { print files, inserted, deleted }'
               )

  echo -e "\n$(c M)line changes$(c) :\n"
  if "${verbose}"; then
    debugInfo=$(echo "${allChanges} ${userChanges}" |
                awk '{ files=$1; inserted=$2; deleted=$3; userFiles=$4; userInserted=$5; userDeleted=$6 } END \
                     {
                       printf( "ALL CHANGES\\n" )
                       printf( "\tfiles changed : %s\\n" , files        )
                       printf( "\tline inserted : %s\\n" , inserted     )
                       printf( "\tline deleted : %s\\n"  , deleted      )
                       printf( "USER CHANGES\\n" )
                       printf( "\tfiles changed : %s\\n" , userFiles    )
                       printf( "\tline inserted : %s\\n" , userInserted )
                       printf( "\tline deleted : %s"     , userDeleted  )
                     }'
              )
    debugLog "${debugInfo}"
    echo ""
  fi

  echo "${allChanges} ${userChanges}" |
       awk '{
              files=$1; inserted=$2; deleted=$3; userFiles=$4; userInserted=$5; userDeleted=$6; fileRate=$4*100/$1; insertRate=$5*100/$2; deleteRate=$6*100/$3
            } END {
              printf( "\tfiles changed : %7.4f%% ( %d/%d ) \n" , fileRate   , userFiles    , files    )
              printf( "\tline inserted : %7.4f%% ( %d/%d ) \n" , insertRate , userInserted , inserted )
              printf( "\tline deleted  : %7.4f%% ( %d/%d ) \n" , deleteRate , userDeleted  , deleted  )
            }' |
       padRight
}

function commitsCount() {
  local allCount
  local userCount
  local debugInfo
  local -a cmd=( git shortlog -s -n )

  allCount=$( "${cmd[@]}" "${GIT_OPT[@]}" | awk '{ sum += $1; } END { print sum; }' )
  userCount="$( "${cmd[@]}" "${GIT_OPT[@]}" --author="${author}" | awk '{sum += $1} END {print sum}' )"

  echo -e "\n$(c M)commits$(c) :\n"
  if "${verbose}"; then
    debugInfo=$(echo -e "${allCount} ${userCount}" |
                awk '{ aCount=$1; uCount=$2 } END \
                     { printf( "COMMITS\\n" )
                       printf( "\tall commit : %s\\n"  , aCount )
                       printf( "\tuser commit : %s" , uCount )
                     }'
              )
    debugLog "${debugInfo}"
    echo ""
  fi

  echo -e "${allCount} ${userCount}" |
  awk '{ aCount=$1; uCount=$2; countRate=$2*100/$1; } END \
       { printf( "\tcommit submitted : %7.4f%% ( %d/%d ) \n" , countRate, uCount, aCount ) }' |
  padRight
}

# main
declare verbose=false
declare lineChanges=false
declare commitsCount=false
declare -a GIT_OPT=()
declare author="$( git config --get user.name )"
declare -r USAGE="NAME
  $(c Cs)${ME}$(c) - to get git statistic for line-changes and commit count

SYNOPSIS
  $(c sY)\$ ${ME} $(c 0Wi)[ OPTIONS ]$(c)

OPTIONS
  $(c G)-a$(c), $(c G)--all$(c)                       show all statistic $(c i)( line-changes and commit count )$(c)
  $(c G)-l$(c), $(c G)--lc$(c), $(c G)--line-change$(c)         show line-changes statistic
  $(c G)-c$(c), $(c G)--cc$(c), $(c G)--commit-count$(c)        show commit count
  $(c G)-u$(c), $(c G)--user$(c), $(c G)--author$(c) $(c Ci)<account>$(c)  specify the account to get statistic for $(c 0i)( default: $(c 0Ci)\$(git config user.name)$(c 0i) )$(c)
  $(c Cs)--$(c) $(c Mi)<GIT_OPT>$(c)                    specify GIT_OPT to filter statistic
                                  $(c Wdi)# e.g. $(c 0Cs)-- $(c 0Mi)--since='1 month ago'$(c) or $(c 0Cs)-- $(c 0Mi)--after='2022-01-01'$(c 0Wdi) etc.$(c)
  $(c G)-h$(c), $(c G)--help$(c)                      show this help message and exit
  $(c G)-v$(c), $(c G)--verbose$(c), $(c G)--debug$(c)          show statistic with more details

EXAMPLE
  $(c Wdi)# to list all statistic for $(c 0Wi)current user$(c)
  $(c Y)\$ ${ME} $(c 0Gi)-a$(c)

  $(c Wdi)# to list line changes for $(c 0Wi)current user $(c 0Wdi)since 1 month ago$(c)
  $(c Y)\$ ${ME} $(c 0Gi)--line-change $(c 0Csi)-- $(c 0Mi)--since='1 month ago'$(c)

  $(c Wdi)# to list line-changes statistic for $(c 0Wi)particular account$(c)
  $(c Y)\$ ${ME} $(c 0Gi)-l -u $(c 0Ci)<account>$(c) | $(c Y)\$ ${ME} $(c 0Gi)--line-change --account $(c 0Ci)<account>$(c)

  $(c Wdi)# to list statistic for $(c 0Wi)current user $(c 0Wdi)with specific GIT_OPT$(c)
  $(c Y)\$ ${ME} $(c 0Gi)-a $(c 0Csi)-- $(c 0Mi)--after='2022-01-01' --before='2023-01-01'$(c)
  $(c Y)\$ ${ME} $(c 0Gi)-l --verbose $(c 0Csi)-- $(c 0Mi)--since='2 weeks 3 days 2 hours 30 minutes 59 seconds ago'$(c)

TIPS
  $(c 0Wi)\`\`\`bash
  $(c 0Wdi)# for macOS$(c)$(c 0Wi)
  \$ brew install gawk && sudo ln -sf /usr/local/bin/gawk /usr/local/bin/awk
  \$ export PATH=\"/usr/local/bin:\$PATH\"
  \`\`\`$(c)
"

[[ 0 = "$#" ]] && showHelp

while test -n "$1"; do
  case "$1" in
    -v | --verbose | --debug   ) verbose=true           ; shift   ;;
    -u | --author  | --user    ) author="$2"            ; shift 2 ;;
    -l | --lc | --line-change  ) lineChanges=true       ; shift   ;;
    -c | --cc | --commit-count ) commitsCount=true      ; shift   ;;
    -a | --all                 ) commitsCount=true;
                                 lineChanges=true;        shift   ;;
    -h                         ) showHelp                         ;;
    --                         ) shift ;
                                 case "$1" in
                                   -h | --help ) showHelp         ;;
                                   *           ) GIT_OPT=("$@")   ;;
                                 esac; break                      ;;
    *                          ) die "invalid option : '$*'"      ;;
  esac
done

isRepo
# show all statistic if no specific statistic type is specified == -a | --all
{ ! "${lineChanges}" && ! "${commitsCount}"; } && {
  lineChanges=true
  commitsCount=true
}

printf "statistics for $(c Csi)%s$(c) - $(c Gi)%s$(c) :\n" "${author}" "$(git config --get remote.origin.url)"

"${verbose}" && {
  debugLog "PARAMS"
  debugLog "\tverbose      : ${verbose}     "
  debugLog "\tGIT_OPT      : ${GIT_OPT[*]}  "
  debugLog "\tauthor       : ${author}      "
  debugLog "\tlineChanges  : ${lineChanges} "
  debugLog "\tcommitsCount : ${commitsCount}"
  echo ''
}

"${lineChanges}"  && lineChangesStat
"${commitsCount}" && commitsCount

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
