#!/usr/bin/env bash
#=============================================================================
#     FileName : git-st
#       Author : marslo.jiao@gmail.com
#      Created : 2024-02-01 03:39:19
#   LastChange : 2024-04-04 19:41:58
#   references : https://stackoverflow.com/q/77919418/2940319
#=============================================================================

declare gdiff
gdiff=$(git --no-pager diff --stat --relative | head -n-1)
awk 'FNR==NR { k=$1; $1=""; map[k]=$0; next } { print $0 map[$2] }' \
    <(echo -e "${gdiff}") <(git status -sb)
# | column -t -s '|' -o '|' | sed -e '1 s/|$//'

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
