#!/bin/bash
# =============================================================================
#   FileName: htmlGenerator.sh
#     Author: marslo.jiao@gmail.com
#    Created: 2020-08-19 22:28:24
# LastChange: 2020-08-19 22:28:57
# =============================================================================

file='header.h'
html='header.html'
temp='temp.h'
patten='^[^/].*enum\s*'
funcName=$(grep -En "${patten}" "${file}" | sed -re "s:${patten}([^\s]+)$:\1:" | sed -e 's/^[[:space:]]*//')
begining=$(sed -n '/'"${patten}"'/=' "${file}" | sed -e 's/^[[:space:]]*//')
ending=$(sed -n '/^\s*}\s*'"${funcName}"'\s*;/=' "${file}" | sed -e 's/^[[:space:]]*//')

title="<h2>&#9670;&nbsp; ${funcName}</h2>"
tfooter=' </tbody> </table> '
theader='''
<table>
  <thead>
    <tr>
      <th style="text-align: center; user-select: none;" align="center"><b>Variable Name</b></th>
      <th style="text-align: center; user-select: none;" align="center"><b>Value</b></th>
      <th style="text-align: center; user-select: none;" align="center"><b>Description</b></th>
    </tr>
  </thead>
'''
warnbox="""
<div class=\"confluence-information-macro confluence-information-macro-warning conf-macro output-block\" data-hasbody=\"true\" data-macro-name=\"warning\">
  <span class=\"aui-icon aui-icon-small aui-iconfont-error confluence-information-macro-icon\"> </span>
    <div class=\"confluence-information-macro-body\">
      <p>this page is generated by <a href=\"${env.BUILD_URL}\" target=\"_blank\">${env.JOB_BASE_NAME} ${env.BUILD_DISPLAY_NAME}</a></p>
    </div>
</div>
"""

cleanEnv() {
  [ -f "${temp}" ] && rm -rf "${temp}"
  [ -f "${html}" ] && rm -rf "${html}"
}

# sed -ne "${begining},${ending}p" "${file}"
awk "NR >= $((begining+1)) && NR <= $((ending-1))" "${file}" > temp.h
tbody="<tbody>"
while IFS= read -r line; do
  # echo "Text read from file: $line"
  if [[ "${line}" =~ ^.*=.*\),.*$ ]]; then
    desc=''
    var=$(echo "${line}" | sed -r 's|^\s*(.*)\s*=\s*(.*)\),.*$|\1|' | xargs)
    value=$(echo "${line}" | sed -r 's|^\s*(.*)\s*=\s*(.*)\),.*$|\2)|' | xargs)
    if [[ "${line}" =~ .*'///<'.* ]]; then
      desc=$(echo "${line}" | sed -r 's|^\s*(.*)\s*=\s*(.*)\),\s*/+<(.*)$|\3|' | sed -r "s|'||g" | sed -e 's/^[[:space:]]*//')
    fi
    tbody="""
    ${tbody}
    <tr>
      <td>${var}</td>
      <td><pre><code>${value}</code></pre></td>
      <td>${desc}</td>
    </tr>
    """
  fi
done < "${temp}"

cleanEnv
echo -e "${warnbox}\n${title}\n${theader}\n${tbody}\n${tfooter}" > "${html}"
