apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.3
controlPlaneEndpoint: "<keepalived-v-ip>:6443"
etcd:
  external:
    endpoints:
      - https://<master-1-ip>:2379
      - https://<master-2-ip>:2379
      - https://<master-3-ip>:2379
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/client.pem
    keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
    - <keepalived-v-ip>
    - <master-1-ip>
    - <master-1-hostname>
    - <master-2-ip>
    - <master-2-hostname>
    - <master-3-ip>
    - <master-3-hostname>
  extraArgs:
    etcd-cafile: /etc/kubernetes/pki/etcd/ca.pem
    etcd-certfile: /etc/kubernetes/pki/etcd/client.pem
    etcd-keyfile: /etc/kubernetes/pki/etcd/client-key.pem
  timeoutForControlPlane: 4m0s
imageRepository: k8s.gcr.io
clusterName: "test-k8s"
