# =============================================================================
#   FileName: nfs-pvc.yaml
#     Author: marslo.jiao@gmail.com
#    Created: 2019-06-17 04:23:43
# LastChange: 2019-08-03 11:13:05
# =============================================================================

kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 1.2.3.4
    path: "/vol/jenkins/DEVOPS-JENKINS"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: jenkins-ci
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: jenkins-pv
