#!/bin/bash
# =============================================================================
#   FileName: belloRPi.sh
#     Author: marslo.fssdw
#      Email: marslo.jiao@gmail.com
#    Created: 2019-03-06 22:07:24
# LastChange: 2019-03-06 22:47:27
# =============================================================================

SED="/bin/sed"
USER="devops"
DEVOPSHOME="/home/${USER}"
TIMESTAMPE=$(date +"%Y%m%d%H%M%S")

function reportError() {
  set +H
  echo -e "\\033[31mERROR: $1 !!\\033[0m"
  set -H
}

function setupUser() {
  if ! id devops > /dev/null; then
    sudo useradd -m -c "DevOps account" devops -s /bin/bash
    echo -e "devops\ndevops" | sudo passwd devops
  fi
}

function setupBasic() {
  sudo ${SED} -i -e "s:^\(devops.*$\):# \1:" /etc/sudoers
  sudo bash -c "echo \"devops  ALL=(ALL:ALL) NOPASSWD:ALL\" >> /etc/sudoers"
  sudo apt install -y policycoreutils jq screenfetch
  sudo cp "/etc/bash.bashrc{,.org.${TIMESTAMPE}}"

if ! grep 'generated by marslo' /etc/bash.bashrc > /dev/null 2>&1; then
sudo bash -c 'cat >> /etc/bash.bashrc' << EOF
# generated by marslo
[ -f /usr/bin/screenfetch ] && /usr/bin/screenfetch
[ -e /lib/terminfo/x/xterm-256color ] && export TERM='xterm-256color'

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- +="pushd ."
alias -- -="popd"
alias ws="cd ~/workspace"
alias la="ls -Al"
alias wa="which -a"
EOF
fi

sudo su devops -c "cat > ~/.inputrc" << EOF
set convert-meta on
set completion-ignore-case on
set show-all-if-ambiguous on
set show-all-if-unmodified on
set mark-symlinked-directories on
set print-completions-horizontally on
EOF

  sudo su devops -c "git config --global user.name marslo"
  sudo su devops -c "git config --global user.email marslo.jiao@gmail.com"
  sudo su devops -c "git config --global alias.st status"
  sudo su devops -c "git config --global alias.br branch"

}

function setupLanguage() {
  sudo bash -c "echo 'Asia/Chongqing' /etc/timezone"
  sudo dpkg-reconfigure -f noninteractive tzdata

  curLocale=$(grep -E -v '#|^$' /etc/locale.gen)
  sudo bash -c "sed -re \"s|($curLocale)|# \1|\" -i /etc/locale.gen"
  sudo bash -c "sed -re 's|.*(en_US.UTF-8 UTF-8)|\1|' -i /etc/locale.gen"
  sudo bash -c "echo -e '\"LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8\"' > /etc/default/locale"
  sudo dpkg-reconfigure --frontend=noninteractive locales

  sudo locale-gen --purge en_US.UTF-8
  sudo locale-gen zh_CN.UTF-8
  sudo locale-gen zh_CN.GBK
  sudo update-locale LC_ALL=en_US.UTF-8
}

function setupSSH() {
  [ ! -d ${DEVOPSHOME}/.ssh ] && sudo su devops -c "mkdir -p ${DEVOPSHOME}/.ssh"
  [ ! -f ${DEVOPSHOME}/.ssh/authorized_keys ] && sudo su devops -c "touch ${DEVOPSHOME}/.ssh/authorized_keys"

sudo su devops -c "cat >> ${DEVOPSHOME}/.ssh/authorized_keys" << EOF
# todo
EOF

sudo su devops -c "cat > ${DEVOPSHOME}/.ssh/config" << EOF
HOST  *
      GSSAPIAuthentication no
      StrictHostKeyChecking no
      IdentityFile   ~/.ssh/devops@fssdw
# todo
EOF

sudo su devops -c "cat > ${DEVOPSHOME}/.ssh/devops@fssdw" << EOF
# todo
EOF

  sudo su devops -c "ln -sf ${DEVOPSHOME}/.ssh/devops@fssdw ${DEVOPSHOME}/.ssh/id_rsa"
  sudo su devops -c "chmod 700 ${DEVOPSHOME}/.ssh"
  sudo su devops -c "chmod 400 ${DEVOPSHOME}/.ssh/{authorized_keys,devops@fssdw,id_rsa}"
  sudo su devops -c "restorecon -Rf ~/.ssh"
}

function setupRPi() {
  if [ ! -f ${SED} ]; then
    reportError "Command $SED cannot be found in system!"
  fi

  setupUser
  setupBasic
  setupLanguage
  setupSSH
}

setupRPi
