#!/bin/bash
# =============================================================================
#   FileName: ssstop
#     Author: marslo.jiao@gmail.com
#    Created: 2018-05-14 15:39:28
# LastChange: 2018-05-14 15:47:25
# =============================================================================

PYTHON2="/usr/bin/python"
SSLOCAL="/usr/local/bin/sslocal"

SSHOME="$HOME/.marslo/ss"
SSLOG="${SSHOME}/logs"

SSJSON="${SSHOME}/ssmarslo.json"
SSPID="${SSHOME}/ssmarslo.pid"
SSLOGFILE="${SSLOG}/ssmarslo.log"
LOGTIME=$(date +"%Y-%m-%d %H:%M:%S")

sudo ${PYTHON2} ${SSLOCAL} -d stop \
                           --pid-file=${SSPID} \
                           --log-file=${SSLOGFILE}

echo -e "${LOGTIME} INFO     Stop local" >> ${SSLOGFILE}
