# =============================================================================
#   FileName: blueocean.yaml
#       Desc: Inspired from https://www.blazemeter.com/blog/how-to-setup-scalable-jenkins-on-top-of-a-kubernetes-cluster
#     Author: marslo.jiao@gmail.com
#    Created: 2018-08-30 17:42:05
# LastChange: 2018-08-30 17:42:32
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: blueocean
  namespace: swcoe-system
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: blueocean
