# =============================================================================
#   FileName: jenkins-service.yaml
#     Author: marslo.jiao@gmail.com
#    Created: 2018-11-09 09:40:29
# LastChange: 2018-11-09 15:40:49
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: devops-jenkins
  namespace: devops-ci
spec:
  type: NodePort
  ports:
    - name: devops-jenkins
      port: 8080
      targetPort: 8080
      nodePort: 30838
    - name: jenkins-agent
      port: 50000
      targetPort: 50000
      nodePort: 30380
    - name: cli-agent
      port: 38238
      targetPort: 38238
      nodePort: 32380
  selector:
    app: devops-jenkins
